---

- name: set up host with standard environment
  hosts: localhost
  #become: true
  #become_user: root

  connection: local

  vars_files:
    - vars/user.yml

  roles:
    - common
    - { role: f24,     when: ansible_os_family == 'RedHat' }
    - { role: macbook, when: ansible_os_family == 'Darwin' }
