---
# docker installation and config

- block:

  - name: install docker
    dnf: name=docker state=present

  - name: start docker
    service: name=docker enabled=yes state=started

  - name: create a docker group
    group: name=docker state=present

  - name: add self to docker group
    user: name={{ logname }} append=yes groups=docker

  tags:
  - docker
