---
- name: get dotfiles repo
  git:
    name=https://github.com/{{ logname }}/dotfiles.git
    dest=/tmp/dotfiles

- name: copy to my home directory
  copy:
    src=/tmp/dotfiles/{{ item }}
    dest="{{ home }}/{{ item }}"
    owner=jsh
    group=jsh
  with_items:
    - .bash-aliases
    - .bash-functions
    - .bash-golang
    - .bash-local
    - .bash-mac
    - .bash-variables

- name: use the new dotfiles
  blockinfile:
    dest: "{{ home }}/.bashrc"
    block: |
      [[ -f ~/.bash-local ]] && . ~/.bash-local
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
