---

- name: get dotfiles repo
  git:
    name=https://github.com/{{ logname }}/dotfiles.git
    dest="{{ home }}/Projects/dotfiles"
    update=yes
  become: true
  become_user: "{{ logname }}"
  tags:
    - dotfiles

- name: symlink dotfiles
  file: src="{{ home }}/Projects/dotfiles/.bash-{{ item }}" dest="{{ home }}/.bash-{{ item }}" state=link
  with_items:
    - aliases
    - functions
    - golang
    - local
    - mac
    - variables
  tags:
    - dotfiles

- name: use the new dotfiles
  blockinfile:
    dest: "{{ home }}/.bashrc"
    block: |
      [[ -f ~/.bash-local ]] && . ~/.bash-local
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  tags:
    - dotfiles
