---
# Virtual Box

- block:

  - name: add vbox config repo
    command: dnf config-manager --add-repo=http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo

  - name: install virtualbox support
    dnf: name={{ item }} state=present
    with_items:
    - dkms
    - kernel-devel
    - VirtualBox-5.1

  - name: install vagrant support
    dnf: name=vagrant-libvirt state=present

  - name: setup driver
    command: /sbin/rcvboxdrv setup

  tags:
  - virtualbox

    #- name: get extension packs
    #shell: cd /opt && wget http://download.virtualbox.org/virtualbox/5.1.0/Oracle_VM_VirtualBox_Extension_Pack-5.1.0-108711.vbox-extpack
  
            #          VirtualBox-5.1-5.1.4_110228_fedora24-1.x86_64.rpm

    #- name: install extension packs
    #shell: command VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-5.1.0-108711.vbox-extpack
