---
# package management

- block:

  - name: get basic packages
    homebrew: name={{ item }} state=latest
    with_items:
    - ansible
    - bash
    - bash-completion
    - binutils
    - coreutils
    - cowsay
    - docker
    - gcc
    - gettext
    - go
    - md5sha1sum
    - mtr
    - pstree
    - readline
    - sloccount
    - ssh-copy-id
    - tree
    - watch

  - name: update homebrew and upgrade all packages
    homebrew: update_homebrew=yes upgrade_all=yes

  become: true
  become_user: "{{ logname }}"
  tags:
  - packages

