#!/bin/bash -eu

sudo systemctl start openssh-server
sudo systemctl enable openssh-server
ssh-keygen
cp .ssh/id_rsa.pub .ssh/authorized_keys


/sbin/rcvboxdrv setup
cd /opt
sudo wget http://download.virtualbox.org/virtualbox/5.1.0/Oracle_VM_VirtualBox_Extension_Pack-5.1.0-108711.vbox-extpack
sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-5.1.0-108711.vbox-extpack
