--
# debug

- block:

  - name: debugging message
    debug: msg="hello {{ logname }}"

  - name: remove /tmp/foo
    file: path=/tmp/foo state=absent

  - name: create /tmp/foo
    file: path=/tmp/foo state=touch

  - name: remove hello repo
    file: dest="{{ home }}/Projects/hello" state=absent

  - name: get hello repo
    git:
      name: https://github.com/jsh/hello.git
      dest: "{{ home }}/Projects/hello"
      update: yes

  become: true
  become_user: "{{ logname }}"

  tags:
  - debug

- block:

  - name: remove /tmp/bar
    file: path=/tmp/bar state=absent

  - name: create /tmp/bar
    file: path=/tmp/bar state=touch

  become: true
  become_user: root

  tags:
  - debug2


- block:

  - name: remove /tmp/mumble
    file: path=/tmp/mumble state=absent

  - name: create /tmp/mumble
    file: path=/tmp/mumble state=touch

# note no becomes

  tags:
  - debug3

