---
# personal dotfiles stuff

- block:
  - name: get dotfiles repo
    git:
      name=https://github.com/{{ logname }}/dotfiles.git
      dest="{{ home }}/Projects/dotfiles"
      update=yes
    become: true
    become_user: "{{ logname }}"
  
  - name: symlink dotfiles
    file: src="{{ home }}/Projects/dotfiles/.bash-{{ item }}" dest="{{ home }}/.bash-{{ item }}" state=link
    with_items:
    - aliases
    - functions
    - golang
    - local
    - mac
    - variables
  
  - name: use the new dotfiles
    blockinfile:
      dest: "{{ home }}/.bashrc"
      block: |
        [[ -r ~/.bash-local ]] && . ~/.bash-local
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
  
  tags:
    - dotfiles
