---
# personal dotfiles stuff

- block:
  - name: get dotfiles repo
    git:
      name=https://github.com/jsh/dotfiles.git
      dest="{{ home }}/Projects/dotfiles"
      update=yes
  
  - name: symlink dotfiles
    file: src="{{ home }}/Projects/dotfiles/.bash-{{ item }}" dest="{{ home }}/.bash-{{ item }}" state=link
    with_items:
    - aliases
    - functions
    - golang
    - local
    - mac
   
  - name: make .bashrc if I need to
    file: path="{{ home }}/.bashrc" state=touch

  - name: use the new dotfiles
    blockinfile:
      dest: "{{ home }}/.bashrc"
      block: |
        [[ -r ~/.bash-local ]] && . ~/.bash-local
      marker: "# {mark} ANSIBLE MANAGED BLOCK"

  become: true
  become_user: "{{ logname }}"
  tags:
    - dotfiles
