---
# configure vi

- block:

  - name: get vundle repo
    git:
      name: https://github.com/VundleVim/Vundle.vim.git
      dest: "{{ home }}/Projects/Vundle.vim"
      update: yes

  - name: make a directory for my vim bundles
    file: name="{{ home }}/.vim/bundle" state=directory
  
  - name: symlink Vundle.vim to my home directory
    file:
      src: "{{ home }}/Projects/Vundle.vim/"
      dest: "{{ home }}/.vim/bundle/Vundle.vim"
      state: link
  
  - name: install .vimrc
    copy: src=files/dot-vimrc dest="{{ home }}/.vimrc"

  become: true
  become_user: "{{ logname }}"
  tags:
  - vundle
